# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_review_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addReviewDialog(object):
    def setupUi(self, addReviewDialog):
        addReviewDialog.setObjectName("addReviewDialog")
        addReviewDialog.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(addReviewDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.reviewtextEdit = QtWidgets.QTextEdit(addReviewDialog)
        self.reviewtextEdit.setObjectName("reviewtextEdit")
        self.verticalLayout.addWidget(self.reviewtextEdit)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.scorelcdNumber = QtWidgets.QLCDNumber(addReviewDialog)
        self.scorelcdNumber.setSmallDecimalPoint(True)
        self.scorelcdNumber.setMode(QtWidgets.QLCDNumber.Dec)
        self.scorelcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.scorelcdNumber.setObjectName("scorelcdNumber")
        self.gridLayout.addWidget(self.scorelcdNumber, 0, 0, 1, 1)
        self.backReviewpushButton = QtWidgets.QPushButton(addReviewDialog)
        self.backReviewpushButton.setObjectName("backReviewpushButton")
        self.gridLayout.addWidget(self.backReviewpushButton, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(addReviewDialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 1, 1, 1)
        self.AddReviewpushButton = QtWidgets.QPushButton(addReviewDialog)
        self.AddReviewpushButton.setObjectName("AddReviewpushButton")
        self.gridLayout.addWidget(self.AddReviewpushButton, 1, 3, 1, 1)
        self.scoredial = QtWidgets.QDial(addReviewDialog)
        self.scoredial.setMaximum(50)
        self.scoredial.setPageStep(1)
        self.scoredial.setProperty("value", 0)
        self.scoredial.setSliderPosition(0)
        self.scoredial.setTracking(True)
        self.scoredial.setWrapping(False)
        self.scoredial.setNotchTarget(3.7)
        self.scoredial.setNotchesVisible(True)
        self.scoredial.setObjectName("scoredial")
        self.gridLayout.addWidget(self.scoredial, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(addReviewDialog)
        QtCore.QMetaObject.connectSlotsByName(addReviewDialog)

    def retranslateUi(self, addReviewDialog):
        _translate = QtCore.QCoreApplication.translate
        addReviewDialog.setWindowTitle(_translate("addReviewDialog", "Dialog"))
        self.reviewtextEdit.setPlaceholderText(_translate("addReviewDialog", "Provide your great review on a market"))
        self.backReviewpushButton.setText(_translate("addReviewDialog", "Back"))
        self.AddReviewpushButton.setText(_translate("addReviewDialog", "Publish review"))
