# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\filter_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filterDialog(object):
    def setupUi(self, filterDialog):
        filterDialog.setObjectName("filterDialog")
        filterDialog.resize(446, 245)
        filterDialog.setMaximumSize(QtCore.QSize(450, 245))
        filterDialog.setWhatsThis("")
        self.verticalLayout = QtWidgets.QVBoxLayout(filterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.winfowTitlelabel = QtWidgets.QLabel(filterDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.winfowTitlelabel.sizePolicy().hasHeightForWidth())
        self.winfowTitlelabel.setSizePolicy(sizePolicy)
        self.winfowTitlelabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.winfowTitlelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.winfowTitlelabel.setObjectName("winfowTitlelabel")
        self.verticalLayout.addWidget(self.winfowTitlelabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.FilterCriterialineEdit = QtWidgets.QLineEdit(filterDialog)
        self.FilterCriterialineEdit.setToolTip("")
        self.FilterCriterialineEdit.setToolTipDuration(-1)
        self.FilterCriterialineEdit.setObjectName("FilterCriterialineEdit")
        self.gridLayout.addWidget(self.FilterCriterialineEdit, 2, 1, 1, 1)
        self.FilterCriterialabel = QtWidgets.QLabel(filterDialog)
        self.FilterCriterialabel.setObjectName("FilterCriterialabel")
        self.gridLayout.addWidget(self.FilterCriterialabel, 2, 0, 1, 1)
        self.FilterListcomboBox = QtWidgets.QComboBox(filterDialog)
        self.FilterListcomboBox.setObjectName("FilterListcomboBox")
        self.gridLayout.addWidget(self.FilterListcomboBox, 0, 1, 1, 1)
        self.FilterListlabel = QtWidgets.QLabel(filterDialog)
        self.FilterListlabel.setMinimumSize(QtCore.QSize(220, 0))
        self.FilterListlabel.setSizeIncrement(QtCore.QSize(0, 0))
        self.FilterListlabel.setObjectName("FilterListlabel")
        self.gridLayout.addWidget(self.FilterListlabel, 0, 0, 1, 1)
        self.BackpushButton = QtWidgets.QPushButton(filterDialog)
        self.BackpushButton.setObjectName("BackpushButton")
        self.gridLayout.addWidget(self.BackpushButton, 3, 0, 1, 1)
        self.AcceptpushButton = QtWidgets.QPushButton(filterDialog)
        self.AcceptpushButton.setObjectName("AcceptpushButton")
        self.gridLayout.addWidget(self.AcceptpushButton, 3, 1, 1, 1)
        self.Ziplabel = QtWidgets.QLabel(filterDialog)
        self.Ziplabel.setObjectName("Ziplabel")
        self.gridLayout.addWidget(self.Ziplabel, 1, 0, 1, 1)
        self.ZiplineEdit = QtWidgets.QLineEdit(filterDialog)
        self.ZiplineEdit.setObjectName("ZiplineEdit")
        self.gridLayout.addWidget(self.ZiplineEdit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(filterDialog)
        QtCore.QMetaObject.connectSlotsByName(filterDialog)

    def retranslateUi(self, filterDialog):
        _translate = QtCore.QCoreApplication.translate
        filterDialog.setWindowTitle(_translate("filterDialog", "Dialog"))
        self.winfowTitlelabel.setText(_translate("filterDialog", "Filter box"))
        self.FilterCriterialineEdit.setWhatsThis(_translate("filterDialog", "Enter the criterion to filter the selection.\n"
"The criterion is entered as a formula:\n"
"> - greater than\n"
"< - less than\n"
">= - greater than or equal\n"
"<= - less than or equal\n"
"= - equal\n"
"Example:\n"
"> 30 will show all records strictly greater than 30\n"
"It\'s best to separate the number from the sign with a space."))
        self.FilterCriterialabel.setText(_translate("filterDialog", "Filter"))
        self.FilterListlabel.setText(_translate("filterDialog", "Filter type"))
        self.BackpushButton.setText(_translate("filterDialog", "Back"))
        self.AcceptpushButton.setText(_translate("filterDialog", "Accept"))
        self.Ziplabel.setText(_translate("filterDialog", "Zip"))
