# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pagination_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_paginationwidget(object):
    def setupUi(self, paginationwidget):
        paginationwidget.setObjectName("paginationwidget")
        paginationwidget.resize(179, 18)
        self.gridLayoutWidget = QtWidgets.QWidget(paginationwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 171, 19))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_page5 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_page5.sizePolicy().hasHeightForWidth())
        self.radioButton_page5.setSizePolicy(sizePolicy)
        self.radioButton_page5.setMaximumSize(QtCore.QSize(45, 16777215))
        self.radioButton_page5.setObjectName("radioButton_page5")
        self.gridLayout.addWidget(self.radioButton_page5, 0, 0, 1, 1)
        self.radioButton_page30 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_page30.setMaximumSize(QtCore.QSize(45, 16777215))
        self.radioButton_page30.setObjectName("radioButton_page30")
        self.gridLayout.addWidget(self.radioButton_page30, 0, 3, 1, 1)
        self.radioButton_page50 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_page50.setMaximumSize(QtCore.QSize(45, 16777215))
        self.radioButton_page50.setObjectName("radioButton_page50")
        self.gridLayout.addWidget(self.radioButton_page50, 0, 4, 1, 1)
        self.radioButton_page20 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_page20.setMaximumSize(QtCore.QSize(45, 16777215))
        self.radioButton_page20.setObjectName("radioButton_page20")
        self.gridLayout.addWidget(self.radioButton_page20, 0, 2, 1, 1)
        self.radioButton_page10 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_page10.setMaximumSize(QtCore.QSize(45, 16777215))
        self.radioButton_page10.setObjectName("radioButton_page10")
        self.gridLayout.addWidget(self.radioButton_page10, 0, 1, 1, 1)

        self.retranslateUi(paginationwidget)
        QtCore.QMetaObject.connectSlotsByName(paginationwidget)

    def retranslateUi(self, paginationwidget):
        _translate = QtCore.QCoreApplication.translate
        paginationwidget.setWindowTitle(_translate("paginationwidget", "Form"))
        self.radioButton_page5.setText(_translate("paginationwidget", "5"))
        self.radioButton_page30.setText(_translate("paginationwidget", "30"))
        self.radioButton_page50.setText(_translate("paginationwidget", "50"))
        self.radioButton_page20.setText(_translate("paginationwidget", "20"))
        self.radioButton_page10.setText(_translate("paginationwidget", "10"))
