# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\register_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 468)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.usernameLabel = QtWidgets.QLabel(Dialog)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(Dialog)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(Dialog)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.firstnameLabel = QtWidgets.QLabel(Dialog)
        self.firstnameLabel.setObjectName("firstnameLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.firstnameLabel)
        self.firstnameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.firstnameLineEdit.setObjectName("firstnameLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.firstnameLineEdit)
        self.lastnameLabel = QtWidgets.QLabel(Dialog)
        self.lastnameLabel.setObjectName("lastnameLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lastnameLabel)
        self.lastnameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.lastnameLineEdit.setObjectName("lastnameLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lastnameLineEdit)
        self.longitudeLabel = QtWidgets.QLabel(Dialog)
        self.longitudeLabel.setObjectName("longitudeLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.longitudeLabel)
        self.longitudeLineEdit = QtWidgets.QLineEdit(Dialog)
        self.longitudeLineEdit.setObjectName("longitudeLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.longitudeLineEdit)
        self.latitudeLabel = QtWidgets.QLabel(Dialog)
        self.latitudeLabel.setObjectName("latitudeLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.latitudeLabel)
        self.latitudeLineEdit = QtWidgets.QLineEdit(Dialog)
        self.latitudeLineEdit.setObjectName("latitudeLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.latitudeLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.registerButton = QtWidgets.QPushButton(Dialog)
        self.registerButton.setObjectName("registerButton")
        self.horizontalLayout.addWidget(self.registerButton)
        self.backButton = QtWidgets.QPushButton(Dialog)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout.addWidget(self.backButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.usernameLabel.setText(_translate("Dialog", "Username"))
        self.passwordLabel.setText(_translate("Dialog", "Password"))
        self.firstnameLabel.setText(_translate("Dialog", "Firstname"))
        self.lastnameLabel.setText(_translate("Dialog", "Lastname"))
        self.longitudeLabel.setText(_translate("Dialog", "Longitude"))
        self.latitudeLabel.setText(_translate("Dialog", "Latitude"))
        self.registerButton.setText(_translate("Dialog", "Register"))
        self.backButton.setText(_translate("Dialog", "Back"))
