# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\user_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserDetailsDialog(object):
    def setupUi(self, UserDetailsDialog):
        UserDetailsDialog.setObjectName("UserDetailsDialog")
        UserDetailsDialog.resize(380, 230)
        UserDetailsDialog.setMinimumSize(QtCore.QSize(380, 230))
        UserDetailsDialog.setMaximumSize(QtCore.QSize(380, 230))
        self.verticalLayout = QtWidgets.QVBoxLayout(UserDetailsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.usernamelabel = QtWidgets.QLabel(UserDetailsDialog)
        self.usernamelabel.setObjectName("usernamelabel")
        self.gridLayout_2.addWidget(self.usernamelabel, 0, 0, 1, 1)
        self.usernamelineEdit = QtWidgets.QLineEdit(UserDetailsDialog)
        self.usernamelineEdit.setReadOnly(True)
        self.usernamelineEdit.setObjectName("usernamelineEdit")
        self.gridLayout_2.addWidget(self.usernamelineEdit, 0, 1, 1, 1)
        self.firstnamelabel = QtWidgets.QLabel(UserDetailsDialog)
        self.firstnamelabel.setObjectName("firstnamelabel")
        self.gridLayout_2.addWidget(self.firstnamelabel, 1, 0, 1, 1)
        self.firstnamelineEdit = QtWidgets.QLineEdit(UserDetailsDialog)
        self.firstnamelineEdit.setReadOnly(True)
        self.firstnamelineEdit.setObjectName("firstnamelineEdit")
        self.gridLayout_2.addWidget(self.firstnamelineEdit, 1, 1, 1, 1)
        self.lastnamelabel = QtWidgets.QLabel(UserDetailsDialog)
        self.lastnamelabel.setObjectName("lastnamelabel")
        self.gridLayout_2.addWidget(self.lastnamelabel, 2, 0, 1, 1)
        self.lastnamelineEdit = QtWidgets.QLineEdit(UserDetailsDialog)
        self.lastnamelineEdit.setReadOnly(True)
        self.lastnamelineEdit.setObjectName("lastnamelineEdit")
        self.gridLayout_2.addWidget(self.lastnamelineEdit, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.coordinateslabel = QtWidgets.QLabel(UserDetailsDialog)
        self.coordinateslabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.coordinateslabel.setAlignment(QtCore.Qt.AlignCenter)
        self.coordinateslabel.setObjectName("coordinateslabel")
        self.verticalLayout.addWidget(self.coordinateslabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.longitudelabel = QtWidgets.QLabel(UserDetailsDialog)
        self.longitudelabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.longitudelabel.setObjectName("longitudelabel")
        self.gridLayout.addWidget(self.longitudelabel, 0, 1, 1, 1)
        self.latitudelabel = QtWidgets.QLabel(UserDetailsDialog)
        self.latitudelabel.setObjectName("latitudelabel")
        self.gridLayout.addWidget(self.latitudelabel, 0, 0, 1, 1)
        self.longitudelineEdit = QtWidgets.QLineEdit(UserDetailsDialog)
        self.longitudelineEdit.setReadOnly(True)
        self.longitudelineEdit.setObjectName("longitudelineEdit")
        self.gridLayout.addWidget(self.longitudelineEdit, 1, 1, 1, 1)
        self.latitudelineEdit = QtWidgets.QLineEdit(UserDetailsDialog)
        self.latitudelineEdit.setReadOnly(True)
        self.latitudelineEdit.setObjectName("latitudelineEdit")
        self.gridLayout.addWidget(self.latitudelineEdit, 1, 0, 1, 1)
        self.backpushButton = QtWidgets.QPushButton(UserDetailsDialog)
        self.backpushButton.setObjectName("backpushButton")
        self.gridLayout.addWidget(self.backpushButton, 2, 0, 1, 1)
        self.logoutpushButton = QtWidgets.QPushButton(UserDetailsDialog)
        self.logoutpushButton.setObjectName("logoutpushButton")
        self.gridLayout.addWidget(self.logoutpushButton, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(UserDetailsDialog)
        QtCore.QMetaObject.connectSlotsByName(UserDetailsDialog)

    def retranslateUi(self, UserDetailsDialog):
        _translate = QtCore.QCoreApplication.translate
        UserDetailsDialog.setWindowTitle(_translate("UserDetailsDialog", "Dialog"))
        self.usernamelabel.setText(_translate("UserDetailsDialog", "User name"))
        self.firstnamelabel.setText(_translate("UserDetailsDialog", "First name"))
        self.lastnamelabel.setText(_translate("UserDetailsDialog", "Last Name"))
        self.coordinateslabel.setText(_translate("UserDetailsDialog", "Coordinates"))
        self.longitudelabel.setText(_translate("UserDetailsDialog", "Longitude"))
        self.latitudelabel.setText(_translate("UserDetailsDialog", "Latitude"))
        self.backpushButton.setText(_translate("UserDetailsDialog", "Back"))
        self.logoutpushButton.setText(_translate("UserDetailsDialog", "Logout"))
