# Form implementation generated from reading ui file '.\GameWindow_raw.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GameWindow(object):
    def setupUi(self, GameWindow):
        GameWindow.setObjectName("GameWindow")
        GameWindow.resize(929, 517)
        GameWindow.setMinimumSize(QtCore.QSize(879, 490))
        GameWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(GameWindow)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.PlayerBoardLabel = QtWidgets.QLabel(parent=GameWindow)
        self.PlayerBoardLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.PlayerBoardLabel.setObjectName("PlayerBoardLabel")
        self.verticalLayout.addWidget(self.PlayerBoardLabel)
        self.PlayerBoard = BoardWidget(parent=GameWindow)
        self.PlayerBoard.setMinimumSize(QtCore.QSize(350, 0))
        self.PlayerBoard.setAutoFillBackground(False)
        self.PlayerBoard.setStyleSheet("border: 2px solid #3498db;\n"
"")
        self.PlayerBoard.setObjectName("PlayerBoard")
        self.verticalLayout.addWidget(self.PlayerBoard)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.CommandpushButton = QtWidgets.QPushButton(parent=GameWindow)
        self.CommandpushButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.CommandpushButton.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.CommandpushButton.setObjectName("CommandpushButton")
        self.verticalLayout_3.addWidget(self.CommandpushButton)
        self.InformationBrowser = QtWidgets.QTextBrowser(parent=GameWindow)
        self.InformationBrowser.setObjectName("InformationBrowser")
        self.verticalLayout_3.addWidget(self.InformationBrowser)
        self.SwitchModeButton = QtWidgets.QPushButton(parent=GameWindow)
        self.SwitchModeButton.setObjectName("SwitchModeButton")
        self.verticalLayout_3.addWidget(self.SwitchModeButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.EnemyBoardLabel = QtWidgets.QLabel(parent=GameWindow)
        self.EnemyBoardLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.EnemyBoardLabel.setObjectName("EnemyBoardLabel")
        self.verticalLayout_2.addWidget(self.EnemyBoardLabel)
        self.EnemyBoard = BoardWidget(parent=GameWindow)
        self.EnemyBoard.setMinimumSize(QtCore.QSize(350, 0))
        self.EnemyBoard.setAutoFillBackground(False)
        self.EnemyBoard.setStyleSheet("border: 2px solid #3498db;\n"
"")
        self.EnemyBoard.setObjectName("EnemyBoard")
        self.verticalLayout_2.addWidget(self.EnemyBoard)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(GameWindow)
        QtCore.QMetaObject.connectSlotsByName(GameWindow)

    def retranslateUi(self, GameWindow):
        _translate = QtCore.QCoreApplication.translate
        GameWindow.setWindowTitle(_translate("GameWindow", "Form"))
        self.PlayerBoardLabel.setText(_translate("GameWindow", "Player Board"))
        self.CommandpushButton.setText(_translate("GameWindow", "PushButton"))
        self.SwitchModeButton.setText(_translate("GameWindow", "SwitchMode"))
        self.EnemyBoardLabel.setText(_translate("GameWindow", "Enemy Board"))
from view.components.BoardWidget import BoardWidget
