# Form implementation generated from reading ui file '.\GameWindow_raw.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GameWindow(object):
    def setupUi(self, GameWindow):
        GameWindow.setObjectName("GameWindow")
        GameWindow.resize(625, 490)
        self.verticalLayout = QtWidgets.QVBoxLayout(GameWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BoardWidget = BoardWidget(parent=GameWindow)
        self.BoardWidget.setAutoFillBackground(True)
        self.BoardWidget.setStyleSheet("border: 2px solid #3498db;\n"
"")
        self.BoardWidget.setObjectName("BoardWidget")
        self.verticalLayout.addWidget(self.BoardWidget)

        self.retranslateUi(GameWindow)
        QtCore.QMetaObject.connectSlotsByName(GameWindow)

    def retranslateUi(self, GameWindow):
        _translate = QtCore.QCoreApplication.translate
        GameWindow.setWindowTitle(_translate("GameWindow", "Form"))
from view.components.BoardWidget import BoardWidget
