# Form implementation generated from reading ui file 'MainWindow_raw.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 320)
        MainWindow.setMinimumSize(QtCore.QSize(402, 320))
        MainWindow.setMaximumSize(QtCore.QSize(402, 341))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(402, 320))
        self.centralwidget.setMaximumSize(QtCore.QSize(0, 320))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.NewGame_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.NewGame_pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.NewGame_pushButton.setObjectName("NewGame_pushButton")
        self.verticalLayout.addWidget(self.NewGame_pushButton)
        self.Leaderboard_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Leaderboard_pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.Leaderboard_pushButton.setObjectName("Leaderboard_pushButton")
        self.verticalLayout.addWidget(self.Leaderboard_pushButton)
        self.Settings_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Settings_pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.Settings_pushButton.setObjectName("Settings_pushButton")
        self.verticalLayout.addWidget(self.Settings_pushButton)
        self.Exit_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Exit_pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.Exit_pushButton.setObjectName("Exit_pushButton")
        self.verticalLayout.addWidget(self.Exit_pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NewGame_pushButton.setText(_translate("MainWindow", "New Game"))
        self.Leaderboard_pushButton.setText(_translate("MainWindow", "Leaderboards"))
        self.Settings_pushButton.setText(_translate("MainWindow", "Settings"))
        self.Exit_pushButton.setText(_translate("MainWindow", "Exit"))
