# Form implementation generated from reading ui file '.\SettingsWindow_raw.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(410, 335)
        SettingsDialog.setMaximumSize(QtCore.QSize(410, 335))
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Sizelabel = QtWidgets.QLabel(parent=SettingsDialog)
        self.Sizelabel.setObjectName("Sizelabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Sizelabel)
        self.SizetextEdit = QtWidgets.QTextEdit(parent=SettingsDialog)
        self.SizetextEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.SizetextEdit.setUndoRedoEnabled(True)
        self.SizetextEdit.setObjectName("SizetextEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SizetextEdit)
        self.AiDifficultylabel = QtWidgets.QLabel(parent=SettingsDialog)
        self.AiDifficultylabel.setObjectName("AiDifficultylabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.AiDifficultylabel)
        self.AIDifficultycomboBox = QtWidgets.QComboBox(parent=SettingsDialog)
        self.AIDifficultycomboBox.setObjectName("AIDifficultycomboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.AIDifficultycomboBox)
        self.ShipCountlabel = QtWidgets.QLabel(parent=SettingsDialog)
        self.ShipCountlabel.setObjectName("ShipCountlabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.ShipCountlabel)
        self.ShipCounttextEdit = QtWidgets.QTextEdit(parent=SettingsDialog)
        self.ShipCounttextEdit.setMaximumSize(QtCore.QSize(312, 191))
        self.ShipCounttextEdit.setObjectName("ShipCounttextEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ShipCounttextEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SettingsDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close|QtWidgets.QDialogButtonBox.StandardButton.Open|QtWidgets.QDialogButtonBox.StandardButton.Reset|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Dialog"))
        self.Sizelabel.setText(_translate("SettingsDialog", "Size"))
        self.SizetextEdit.setPlaceholderText(_translate("SettingsDialog", "10x10"))
        self.AiDifficultylabel.setText(_translate("SettingsDialog", "AI Difficulty"))
        self.ShipCountlabel.setText(_translate("SettingsDialog", "ShipCount"))
